######################################################################
# Automatically generated by qmake (3.0) sam. sept. 26 19:53:44 2015
######################################################################

TEMPLATE = app
TARGET = dbstats
INCLUDEPATH += .
INCLUDEPATH += ./include

# Input
SOURCES += main.cpp source/mainwindow.cpp
HEADERS += include/mainwindow.h 

QT += sql widgets
